Repository DioxusLabs/dioxus, pull requests merged in 2022-12, with the labels that each got.

#673 fix: dont send initialize until WS is connected
  packages/liveview/src/main.js
Labels: liveview

#685 Fix copy paste error in docs
  packages/desktop/src/lib.rs
Labels: documentation

#684 fix tui benchmark
  packages/tui/benches/update.rs
Labels: bug
