Repository DioxusLabs/dioxus, pull requests merged in 2022-10, with the labels that each got.

#576 fix: Remove a Node listeners when it is removed
  packages/native-core/src/real_dom.rs
Labels: hacktoberfest-accepted

#577 Fix attribute value in macro
  packages/core/src/arbitrary_value.rs
  packages/core/src/lib.rs
  packages/core/src/nodes.rs
  packages/rsx/src/template.rs
Labels: bug

#591 fix inserting dynamic nodes after fragments
  packages/interpreter/src/interpreter.js
Labels: bug, web

#578 Refactor Mutations and simplify Templates
  packages/core/src/diff.rs
  packages/core/src/dynamic_template_context.rs
  packages/core/src/events.rs
  packages/core/src/lib.rs
  packages/core/src/mutations.rs
  packages/core/src/nodes.rs
  packages/core/src/scopes.rs
  packages/core/src/template.rs
  packages/core/src/virtual_dom.rs
  packages/desktop/src/events.rs
  packages/dioxus/tests/create_dom.rs
  packages/dioxus/tests/diffing.rs
  packages/dioxus/tests/earlyabort.rs
  packages/dioxus/tests/lifecycle.rs
  packages/dioxus/tests/passthru.rs
  packages/dioxus/tests/sharedstate.rs
  packages/dioxus/tests/vdom_rebuild.rs
  packages/interpreter/src/bindings.rs
  packages/interpreter/src/interpreter.js
  packages/liveview/src/events.rs
  packages/liveview/src/interpreter.js
  packages/native-core-macro/src/lib.rs
  packages/native-core-macro/tests/called_minimally_on_build.rs
  packages/native-core-macro/tests/change_nodes.rs
  packages/native-core-macro/tests/initial_build.rs
  packages/native-core-macro/tests/peristant_iterator.rs
  packages/native-core-macro/tests/update_state.rs
  packages/native-core/Cargo.toml
  packages/native-core/src/lib.rs
  packages/native-core/src/node_ref.rs
  packages/native-core/src/real_dom.rs
  packages/native-core/src/state.rs
  packages/native-core/src/template.rs
  packages/native-core/src/utils.rs
  packages/rsx/src/template.rs
  packages/ssr/src/lib.rs
  packages/tui/examples/tui_colorpicker.rs
  packages/tui/examples/tui_components.rs
  packages/tui/src/focus.rs
  packages/tui/src/hooks.rs
  packages/tui/src/layout.rs
  packages/tui/src/lib.rs
  packages/web/src/dom.rs
  packages/web/src/rehydrate.rs
Labels: breaking, blocker
